version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ci_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci_app
    depends_on:
      - db
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      DB_DRIVER: ${DB_DRIVER}
      DB_DSN: ${DB_DSN}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
